
// Code generated by stanc v2.30.1
#include <stan/model/model_header.hpp>
namespace strength_model_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 16> locations_array__ = 
{" (found before start of program)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 22, column 2 to column 16)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 23, column 2 to column 22)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 24, column 2 to column 35)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 44, column 2 to column 75)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 31, column 2 to column 57)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 34, column 2 to column 71)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 37, column 2 to column 52)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 38, column 2 to column 55)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 7, column 2 to column 29)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 8, column 22 to column 32)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 8, column 2 to column 48)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 11, column 2 to column 25)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 14, column 2 to column 11)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 15, column 2 to column 24)",
 " (in '/Users/ddifrancesco/Github/DCE_guidance/tmp/strength_model.stan', line 16, column 2 to column 26)"};




class strength_model_model final : public model_base_crtp<strength_model_model> {

 private:
  int n_strength;
  Eigen::Matrix<double, -1, 1> strength_meas_data__;
  double error;
  double m_s;
  double sd_s;
  double rate_s; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> strength_meas{nullptr, 0};
 
 public:
  ~strength_model_model() { }
  
  inline std::string model_name() const final { return "strength_model_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.1", "stancflags = "};
  }
  
  
  strength_model_model(stan::io::var_context& context__,
                       unsigned int random_seed__ = 0,
                       std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "strength_model_model_namespace::strength_model_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 9;
      context__.validate_dims("data initialization","n_strength","int",
           std::vector<size_t>{});
      n_strength = std::numeric_limits<int>::min();
      
      
      current_statement__ = 9;
      n_strength = context__.vals_i("n_strength")[(1 - 1)];
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "n_strength",
                                            n_strength, 1);
      current_statement__ = 10;
      stan::math::validate_non_negative_index("strength_meas", "n_strength",
                                              n_strength);
      current_statement__ = 11;
      context__.validate_dims("data initialization","strength_meas","double",
           std::vector<size_t>{static_cast<size_t>(n_strength)});
      strength_meas_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(n_strength,
          std::numeric_limits<double>::quiet_NaN());
      new (&strength_meas) Eigen::Map<Eigen::Matrix<double, -1, 1>>(strength_meas_data__.data(), n_strength);
        
      
      {
        std::vector<local_scalar_t__> strength_meas_flat__;
        current_statement__ = 11;
        strength_meas_flat__ = context__.vals_r("strength_meas");
        current_statement__ = 11;
        pos__ = 1;
        current_statement__ = 11;
        for (int sym1__ = 1; sym1__ <= n_strength; ++sym1__) {
          current_statement__ = 11;
          stan::model::assign(strength_meas,
            strength_meas_flat__[(pos__ - 1)],
            "assigning variable strength_meas", stan::model::index_uni(sym1__));
          current_statement__ = 11;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "strength_meas",
                                            strength_meas, 0);
      current_statement__ = 12;
      context__.validate_dims("data initialization","error","double",
           std::vector<size_t>{});
      error = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 12;
      error = context__.vals_r("error")[(1 - 1)];
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "error", error, 0);
      current_statement__ = 13;
      context__.validate_dims("data initialization","m_s","double",
           std::vector<size_t>{});
      m_s = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 13;
      m_s = context__.vals_r("m_s")[(1 - 1)];
      current_statement__ = 14;
      context__.validate_dims("data initialization","sd_s","double",
           std::vector<size_t>{});
      sd_s = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 14;
      sd_s = context__.vals_r("sd_s")[(1 - 1)];
      current_statement__ = 14;
      stan::math::check_greater_or_equal(function__, "sd_s", sd_s, 0);
      current_statement__ = 15;
      context__.validate_dims("data initialization","rate_s","double",
           std::vector<size_t>{});
      rate_s = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 15;
      rate_s = context__.vals_r("rate_s")[(1 - 1)];
      current_statement__ = 15;
      stan::math::check_greater_or_equal(function__, "rate_s", rate_s, 0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "strength_model_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ strength = DUMMY_VAR__;
      current_statement__ = 1;
      strength = in__.template read<local_scalar_t__>();
      local_scalar_t__ strength_m_log = DUMMY_VAR__;
      current_statement__ = 2;
      strength_m_log = in__.template read<local_scalar_t__>();
      local_scalar_t__ strength_sd_log = DUMMY_VAR__;
      current_statement__ = 3;
      strength_sd_log = in__.template read_constrain_lb<local_scalar_t__, 
                          jacobian__>(0, lp__);
      {
        current_statement__ = 5;
        lp_accum__.add(
          stan::math::normal_lpdf<false>(strength_meas, strength, error));
        current_statement__ = 6;
        lp_accum__.add(
          stan::math::lognormal_lpdf<false>(strength, strength_m_log,
            strength_sd_log));
        current_statement__ = 7;
        lp_accum__.add(
          stan::math::normal_lpdf<false>(strength_m_log, m_s, sd_s));
        current_statement__ = 8;
        lp_accum__.add(
          stan::math::exponential_lpdf<false>(strength_sd_log, rate_s));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "strength_model_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double strength = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      strength = in__.template read<local_scalar_t__>();
      double strength_m_log = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      strength_m_log = in__.template read<local_scalar_t__>();
      double strength_sd_log = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      strength_sd_log = in__.template read_constrain_lb<local_scalar_t__, 
                          jacobian__>(0, lp__);
      out__.write(strength);
      out__.write(strength_m_log);
      out__.write(strength_sd_log);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double strength_post_pred = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      strength_post_pred = stan::math::lognormal_rng(strength_m_log,
                             strength_sd_log, base_rng__);
      out__.write(strength_post_pred);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ strength = DUMMY_VAR__;
      strength = in__.read<local_scalar_t__>();
      out__.write(strength);
      local_scalar_t__ strength_m_log = DUMMY_VAR__;
      strength_m_log = in__.read<local_scalar_t__>();
      out__.write(strength_m_log);
      local_scalar_t__ strength_sd_log = DUMMY_VAR__;
      strength_sd_log = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, strength_sd_log);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"strength", "strength_m_log",
      "strength_sd_log", "strength_post_pred"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "strength");
    param_names__.emplace_back(std::string() + "strength_m_log");
    param_names__.emplace_back(std::string() + "strength_sd_log");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "strength_post_pred");
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "strength");
    param_names__.emplace_back(std::string() + "strength_m_log");
    param_names__.emplace_back(std::string() + "strength_sd_log");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "strength_post_pred");
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"strength\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"strength_m_log\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"strength_sd_log\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"strength_post_pred\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"strength\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"strength_m_log\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"strength_sd_log\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"strength_post_pred\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((1 + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * 1;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((1 + 1) + 1);
      const size_t num_transformed = emit_transformed_parameters * 0;
      const size_t num_gen_quantities = emit_generated_quantities * 1;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 3> names__{"strength",
      "strength_m_log", "strength_sd_log"};
      const std::array<Eigen::Index, 3> constrain_param_sizes__{1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = strength_model_model_namespace::strength_model_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return strength_model_model_namespace::profiles__;
}

#endif


